version: '2'
services:
  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build: ./docker
    container_name: app
    ports:
     - "80:80"
    volumes:
     - ./webroot:/home/dev/www
     - ./mysql:/var/lib/mysql
    links:
      - db:app